### ISSUE TITLE
安装django_auth_ldap 报错，解决

### ISSUE THREAD

**Issue by hequan2017** [getway/diting#1]
Python 3.6.5

安装django_auth_ldap 报错

其实是安装 python-ldap  报错，查询 https://www.python-ldap.org 介绍，
CentOS

Packages for building:

# yum groupinstall "Development tools"
# yum install openldap-devel python-devel

安装完后，可正常安装。

**Comment by hequan2017** [comment]
(venv3) [root@devops utils]# python3 ../apps/manage.py makemigrations common users perms navis
Traceback (most recent call last):
  File "../apps/manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/venv3/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/opt/venv3/lib/python3.6/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/opt/venv3/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/opt/venv3/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/venv3/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/diting/apps/diting/settings.py", line 17, in <module>
    from django_auth_ldap.config import LDAPSearch
  File "/opt/venv3/lib/python3.6/site-packages/django_auth_ldap/config.py", line 40, in <module>
    import ldap.filter
  File "/opt/venv3/lib/python3.6/site-packages/ldap/filter.py", line 12, in <module>
    from ldap.functions import strf_secs
  File "/opt/venv3/lib/python3.6/site-packages/ldap/functions.py", line 19, in <module>
    from ldap import LDAPError
ImportError: cannot import name 'LDAPError'

初始化数据库报错。
Python 3.6.5
